# Generated by Django 5.2.6 on 2026-03-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, db_index=True, default="", max_length=161),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="user",
            name="identify_code",
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="identify_name",
            field=models.CharField(blank=True, db_index=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_profile_completed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(is_profile_completed=False)
                    | (
                        ~models.Q(first_name="")
                        & ~models.Q(last_name="")
                        & ~models.Q(display_name="")
                        & ~models.Q(identify_name__isnull=True)
                        & ~models.Q(identify_name="")
                        & ~models.Q(identify_code__isnull=True)
                        & ~models.Q(identify_code="")
                        & models.Q(profile_completed_at__isnull=False)
                    )
                ),
                name="accounts_user_profile_completed_fields_check",
            ),
        ),
    ]
