# Generated by Django 5.2.6 on 2026-03-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_email_verification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': []},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='identify_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
