# Generated by Django 5.2.6 on 2026-03-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_redundant_indexes_and_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
