# Generated by Django 5.2.13 on 2026-05-12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebSocketTicket",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("auth_version", models.PositiveIntegerField()),
                ("scope", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="websocket_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "realtime_websocket_ticket",
                "ordering": [],
            },
        ),
        migrations.AddIndex(
            model_name="websocketticket",
            index=models.Index(fields=["user", "used_at", "expires_at"], name="rt_ws_ticket_user_used_exp"),
        ),
    ]
