# Generated by Django 5.2.6 on 2026-04-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('FRIEND_REQUEST', 'Friend Request'), ('FRIEND_ACCEPTED', 'Friend Accepted'), ('TRIP_INVITATION', 'Trip Invitation'), ('TRIP_INVITATION_ACCEPTED', 'Trip Invitation Accepted'), ('TRIP_INVITATION_DECLINED', 'Trip Invitation Declined'), ('TRIP_CANCELLED', 'Trip Cancelled'), ('TRIP_MEMBER_REMOVED', 'Trip Member Removed')], max_length=50),
        ),
    ]
