# -------- Base Image --------
FROM node:22-alpine AS deps

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

# -------- Build Stage --------
FROM node:22-alpine AS builder

WORKDIR /app

ARG NEXT_PUBLIC_API_BASE_URL=http://backend:8000
ARG NEXT_PUBLIC_APP_BASE_URL=https://goplan.quangmin.me
ARG NEXT_PUBLIC_WS_URL=wss://api.quangmin.me

ENV NEXT_TELEMETRY_DISABLED=1 \
    NEXT_PRIVATE_BUILD_WORKER_COUNT=1 \
    NODE_OPTIONS=--max-old-space-size=1536 \
    NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL \
    NEXT_PUBLIC_APP_BASE_URL=$NEXT_PUBLIC_APP_BASE_URL \
    NEXT_PUBLIC_WS_URL=$NEXT_PUBLIC_WS_URL

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# -------- Runtime Stage --------
FROM node:22-alpine AS runtime

WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    HOSTNAME=0.0.0.0 \
    PORT=3000

COPY --from=builder /app ./

CMD ["npm", "run", "start"]
