# Generated by Codex on 2026-05-11

from django.db import migrations, models


def backfill_updated_at(apps, schema_editor):
    ChatMessage = apps.get_model("chat", "ChatMessage")
    ChatMessage.objects.filter(updated_at__isnull=True).update(
        updated_at=models.F("created_at")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_message_deletions"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="updated_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(backfill_updated_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="chatmessage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["trip", "updated_at", "id"],
                name="chat_chatme_trip_id_d13dbb_idx",
            ),
        ),
    ]
