# Generated by Django 5.2.13 on 2026-05-11 16:30

from django.conf import settings
from django.db import migrations, models


def keep_latest_reaction_per_user(apps, schema_editor):
    MessageReaction = apps.get_model("chat", "MessageReaction")
    seen_keys = set()
    duplicate_ids = []

    reactions = MessageReaction.objects.order_by(
        "message_id",
        "user_id",
        "-created_at",
        "-id",
    ).values_list("id", "message_id", "user_id")

    for reaction_id, message_id, user_id in reactions:
        key = (message_id, user_id)
        if key in seen_keys:
            duplicate_ids.append(reaction_id)
        else:
            seen_keys.add(key)

    if duplicate_ids:
        MessageReaction.objects.filter(id__in=duplicate_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_message_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="messagereaction",
            name="chat_unique_message_user_emoji",
        ),
        migrations.RunPython(
            keep_latest_reaction_per_user,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="messagereaction",
            constraint=models.UniqueConstraint(
                fields=("message", "user"),
                name="chat_unique_message_user_reaction",
            ),
        ),
    ]
