# Generated by Django 5.2.13 on 2026-05-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_enforce_single_reaction_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='ai_status',
            field=models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('ERROR', 'Error')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_kind',
            field=models.CharField(choices=[('USER', 'User'), ('AI', 'AI')], default='USER', max_length=8),
        ),
    ]
