from __future__ import annotations

AI_CONFIRMATION_CAPTAIN = "CAPTAIN"
AI_CONFIRMATION_TRANSFER_PAYER = "TRANSFER_PAYER"
AI_CONFIRMATION_TRANSFER_RECIPIENT = "TRANSFER_RECIPIENT"
AI_CONFIRMATION_TIMELINE_ACTIVITY_STATUS = "TIMELINE_ACTIVITY_STATUS"

AI_ACTION_TIMELINE_ACTIVITY_CREATE = "timeline.activity.create"
AI_ACTION_TIMELINE_ACTIVITY_UPDATE = "timeline.activity.update"
AI_ACTION_TIMELINE_ACTIVITY_DELETE = "timeline.activity.delete"
AI_ACTION_TIMELINE_ACTIVITY_STATUS_UPDATE = "timeline.activity.status.update"
AI_ACTION_EXPENSE_CREATE = "expense.create"
AI_ACTION_EXPENSE_UPDATE = "expense.update"
AI_ACTION_EXPENSE_DELETE = "expense.delete"
AI_ACTION_EXPENSE_CONTRIBUTION_SET = "expense.contribution.set"
AI_ACTION_SETTLEMENT_FINALIZE = "settlement.finalize"
AI_ACTION_SETTLEMENT_REOPEN = "settlement.reopen"
AI_ACTION_SETTLEMENT_TRANSFER_MARK_SENT = "settlement.transfer.mark_sent"
AI_ACTION_SETTLEMENT_TRANSFER_CONFIRM_RECEIVED = (
    "settlement.transfer.confirm_received"
)

CAPTAIN_MANAGED_ACTIONS = {
    AI_ACTION_TIMELINE_ACTIVITY_CREATE,
    AI_ACTION_TIMELINE_ACTIVITY_UPDATE,
    AI_ACTION_TIMELINE_ACTIVITY_DELETE,
    AI_ACTION_EXPENSE_CREATE,
    AI_ACTION_EXPENSE_UPDATE,
    AI_ACTION_EXPENSE_DELETE,
    AI_ACTION_EXPENSE_CONTRIBUTION_SET,
    AI_ACTION_SETTLEMENT_FINALIZE,
    AI_ACTION_SETTLEMENT_REOPEN,
}

TIMELINE_ACTIVITY_STATUS_ACTIONS = {
    AI_ACTION_TIMELINE_ACTIVITY_STATUS_UPDATE,
}

TRANSFER_PAYER_ACTIONS = {
    AI_ACTION_SETTLEMENT_TRANSFER_MARK_SENT,
}

TRANSFER_RECIPIENT_ACTIONS = {
    AI_ACTION_SETTLEMENT_TRANSFER_CONFIRM_RECEIVED,
}

SUPPORTED_AI_ACTIONS = (
    CAPTAIN_MANAGED_ACTIONS
    | TIMELINE_ACTIVITY_STATUS_ACTIONS
    | TRANSFER_PAYER_ACTIONS
    | TRANSFER_RECIPIENT_ACTIONS
)
