# Generated by Django 5.2.13 on 2026-05-23 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0009_trip_budget_estimate_non_negative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_by_display_name_snapshot', models.CharField(blank=True, default='', max_length=161)),
                ('uploaded_by_identify_tag_snapshot', models.CharField(blank=True, max_length=31, null=True)),
                ('original_filename', models.CharField(blank=True, default='', max_length=160)),
                ('original_width', models.PositiveIntegerField()),
                ('original_height', models.PositiveIntegerField()),
                ('thumbnail', models.ImageField(upload_to='trip-photos')),
                ('medium', models.ImageField(upload_to='trip-photos')),
                ('thumbnail_width', models.PositiveIntegerField()),
                ('thumbnail_height', models.PositiveIntegerField()),
                ('medium_width', models.PositiveIntegerField()),
                ('medium_height', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trips.trip')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['trip', '-created_at'], name='mem_photo_trip_created_idx'), models.Index(fields=['uploaded_by', '-created_at'], name='mem_photo_user_created_idx')],
            },
        ),
    ]
