# Generated by Django 5.2.13 on 2026-05-27 03:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
        ('trips', '0009_trip_budget_estimate_non_negative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripMemoryVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by_display_name_snapshot', models.CharField(blank=True, default='', max_length=161)),
                ('created_by_identify_tag_snapshot', models.CharField(blank=True, max_length=31, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('rendering', 'Rendering'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='queued', max_length=16)),
                ('source_mode', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], max_length=16)),
                ('source_photo_ids', models.JSONField(default=list)),
                ('source_photo_count', models.PositiveIntegerField(default=0)),
                ('music_key', models.CharField(max_length=80)),
                ('video_file', models.FileField(blank=True, max_length=220, null=True, upload_to='trip-memory-videos')),
                ('poster_file', models.FileField(blank=True, max_length=220, null=True, upload_to='trip-memory-videos')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('render_error_code', models.CharField(blank=True, default='', max_length=64)),
                ('render_error_message', models.CharField(blank=True, default='', max_length=240)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('share_enabled', models.BooleanField(default=False)),
                ('share_slug', models.CharField(blank=True, max_length=96, null=True, unique=True)),
                ('share_created_at', models.DateTimeField(blank=True, null=True)),
                ('render_started_at', models.DateTimeField(blank=True, null=True)),
                ('render_finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_memory_videos', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_videos', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['trip', '-created_at'], name='mem_video_trip_created_idx'), models.Index(fields=['created_by', '-created_at'], name='mem_video_user_created_idx')],
            },
        ),
    ]
