# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memories", "0002_trip_memory_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="tripmemoryvideo",
            name="render_recovery_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
