# Generated by Django 5.2.6 on 2026-04-16 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('currency_code', models.CharField(default='VND', max_length=3)),
                ('budget_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNING', max_length=12)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trip_invitations', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_trip_invitations', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('CAPTAIN', 'Captain'), ('MEMBER', 'Member')], max_length=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('LEFT', 'Left'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=8)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='trip_end_date_gte_start_date'),
        ),
        migrations.AddIndex(
            model_name='tripinvitation',
            index=models.Index(fields=['trip', 'status'], name='trips_tripi_trip_id_93ff53_idx'),
        ),
        migrations.AddIndex(
            model_name='tripinvitation',
            index=models.Index(fields=['invitee', 'status'], name='trips_tripi_invitee_b52846_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripinvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('trip', 'invitee'), name='tripinvitation_unique_pending_per_trip'),
        ),
        migrations.AddIndex(
            model_name='tripmember',
            index=models.Index(fields=['trip', 'status'], name='trips_tripm_trip_id_12f5f0_idx'),
        ),
        migrations.AddIndex(
            model_name='tripmember',
            index=models.Index(fields=['user', 'status'], name='trips_tripm_user_id_310658_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripmember',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('trip', 'user'), name='tripmember_unique_active_per_trip'),
        ),
    ]
