# Generated by Django 5.2.6 on 2026-04-20

from django.db import migrations, models


def migrate_legacy_google_destination_data(apps, schema_editor):
    Trip = apps.get_model("trips", "Trip")

    Trip.objects.exclude(destination_provider_id="").update(destination_provider="google")
    Trip.objects.filter(cover_image_url__startswith="/api/places/photo").update(cover_image_url="")


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_trip_place_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="destination_provider",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.RenameField(
            model_name="trip",
            old_name="destination_place_id",
            new_name="destination_provider_id",
        ),
        migrations.RunPython(
            migrate_legacy_google_destination_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]

