# Generated by Django 5.2.6 on 2026-04-25 15:31

import django.db.models.deletion
import uuid
from datetime import timedelta

from django.conf import settings
from django.db import migrations, models


TIMELINE_STARTER_DAY_COUNT = 2


def create_starter_days_for_existing_trips(apps, schema_editor):
    Trip = apps.get_model("trips", "Trip")
    TimelineSection = apps.get_model("trips", "TimelineSection")
    for trip in Trip.objects.all().iterator():
        if not trip.start_date or not trip.end_date:
            continue
        current = trip.start_date
        index = 0
        while current <= trip.end_date and index < TIMELINE_STARTER_DAY_COUNT:
            TimelineSection.objects.create(
                trip=trip,
                kind="SYSTEM_DAY",
                section_date=current,
                label=f"Day {index + 1}",
                is_label_custom=False,
                position=0,
            )
            current = current + timedelta(days=1)
            index += 1


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineCustomType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('normalized_name', models.CharField(max_length=40)),
                ('color_token', models.CharField(default='slate', max_length=24)),
                ('icon_key', models.CharField(default='tag', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_custom_types', to='trips.trip')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('SYSTEM_DAY', 'System Day'), ('SPECIAL_DAY', 'Special Day')], max_length=16)),
                ('section_date', models.DateField()),
                ('label', models.CharField(max_length=120)),
                ('is_label_custom', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_sections', to='trips.trip')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section_date', 'position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=140)),
                ('time_mode', models.CharField(choices=[('ALL_DAY', 'All Day'), ('AT_TIME', 'At Time'), ('TIME_RANGE', 'Time Range')], max_length=16)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=16)),
                ('system_type', models.CharField(blank=True, default='', max_length=32)),
                ('position', models.PositiveIntegerField(default=0)),
                ('location_mode', models.CharField(choices=[('MANUAL', 'Manual'), ('STRUCTURED', 'Structured')], default='MANUAL', max_length=16)),
                ('location_label', models.CharField(blank=True, default='', max_length=200)),
                ('location_note', models.CharField(blank=True, default='', max_length=200)),
                ('place_provider', models.CharField(blank=True, default='', max_length=16)),
                ('place_provider_id', models.CharField(blank=True, default='', max_length=255)),
                ('place_title', models.CharField(blank=True, default='', max_length=200)),
                ('place_address', models.CharField(blank=True, default='', max_length=255)),
                ('place_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('place_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('meeting_point', models.CharField(blank=True, default='', max_length=200)),
                ('contact_name', models.CharField(blank=True, default='', max_length=120)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=32)),
                ('booking_reference', models.CharField(blank=True, default='', max_length=120)),
                ('external_link', models.URLField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_timeline_activities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_activities', to='trips.trip')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('custom_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='trips.timelinecustomtype')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trips.timelinesection')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineActivityReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offset_minutes_before', models.PositiveIntegerField()),
                ('due_at_utc', models.DateTimeField(db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='trips.timelineactivity')),
            ],
            options={
                'ordering': ['offset_minutes_before', 'created_at'],
                'indexes': [models.Index(fields=['sent_at', 'due_at_utc'], name='trips_timel_sent_at_c92344_idx')],
                'constraints': [models.UniqueConstraint(fields=('activity', 'offset_minutes_before', 'due_at_utc'), name='timeline_activity_reminder_unique_due_offset')],
            },
        ),
        migrations.AddIndex(
            model_name='timelinecustomtype',
            index=models.Index(fields=['trip', 'is_active'], name='trips_timel_trip_id_b94ebd_idx'),
        ),
        migrations.AddConstraint(
            model_name='timelinecustomtype',
            constraint=models.UniqueConstraint(fields=('trip', 'normalized_name'), name='timeline_custom_type_unique_name_per_trip'),
        ),
        migrations.AddIndex(
            model_name='timelinesection',
            index=models.Index(fields=['trip', 'section_date', 'position'], name='trips_timel_trip_id_bd3285_idx'),
        ),
        migrations.AddIndex(
            model_name='timelinesection',
            index=models.Index(fields=['trip', 'kind'], name='trips_timel_trip_id_2a46aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='timelinesection',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'SYSTEM_DAY')), fields=('trip', 'section_date'), name='timeline_section_unique_system_day_per_date'),
        ),
        migrations.AddIndex(
            model_name='timelineactivity',
            index=models.Index(fields=['section', 'position'], name='trips_timel_section_96bd58_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineactivity',
            index=models.Index(fields=['trip', 'status'], name='trips_timel_trip_id_ed7937_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineactivity',
            index=models.Index(fields=['trip', 'assignee_user'], name='trips_timel_trip_id_6638c8_idx'),
        ),
        migrations.RunPython(
            create_starter_days_for_existing_trips,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
