# Generated by Django 5.2.6 on 2026-04-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_timeline_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineactivity',
            name='time_mode',
            field=models.CharField(choices=[('ALL_DAY', 'All Day'), ('FLEXIBLE', 'Flexible'), ('AT_TIME', 'At Time'), ('TIME_RANGE', 'Time Range')], max_length=16),
        ),
    ]
