# Generated by Codex on 2026-04-28

from django.db import migrations, models
from django.db.models import Count


def merge_duplicate_timeline_sections(apps, schema_editor):
    TimelineSection = apps.get_model("trips", "TimelineSection")
    TimelineActivity = apps.get_model("trips", "TimelineActivity")

    duplicate_groups = (
        TimelineSection.objects
        .values("trip_id", "section_date")
        .annotate(section_count=Count("id"))
        .filter(section_count__gt=1)
    )

    for group in duplicate_groups:
        sections = list(
            TimelineSection.objects
            .filter(trip_id=group["trip_id"], section_date=group["section_date"])
            .order_by("position", "created_at", "id")
        )
        section_ids = [section.pk for section in sections]
        activity_counts = {
            row["section_id"]: row["activity_count"]
            for row in (
                TimelineActivity.objects
                .filter(section_id__in=section_ids)
                .values("section_id")
                .annotate(activity_count=Count("id"))
            )
        }

        keeper = sorted(
            sections,
            key=lambda section: (
                0 if activity_counts.get(section.pk, 0) > 0 else 1,
                section.position,
                section.created_at,
                str(section.pk),
            ),
        )[0]
        duplicates = [section for section in sections if section.pk != keeper.pk]

        ordered_activity_ids = []
        for section in sections:
            ordered_activity_ids.extend(
                TimelineActivity.objects
                .filter(section=section)
                .order_by("position", "created_at", "id")
                .values_list("id", flat=True)
            )

        for position, activity_id in enumerate(ordered_activity_ids):
            TimelineActivity.objects.filter(pk=activity_id).update(
                section_id=keeper.pk,
                position=position,
            )

        TimelineSection.objects.filter(pk__in=[section.pk for section in duplicates]).delete()
        if keeper.position != 0:
            keeper.position = 0
            keeper.save(update_fields=["position", "updated_at"])


class Migration(migrations.Migration):
    dependencies = [
        ("trips", "0006_alter_timelineactivity_time_mode"),
    ]

    operations = [
        migrations.RunPython(
            merge_duplicate_timeline_sections,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="timelinesection",
            name="timeline_section_unique_system_day_per_date",
        ),
        migrations.AddConstraint(
            model_name="timelinesection",
            constraint=models.UniqueConstraint(
                fields=("trip", "section_date"),
                name="timeline_section_unique_date_per_trip",
            ),
        ),
        migrations.RemoveIndex(
            model_name="timelinesection",
            name="trips_timel_trip_id_2a46aa_idx",
        ),
        migrations.RemoveField(
            model_name="timelinesection",
            name="kind",
        ),
    ]
