# Generated by Django 5.2.6 on 2026-05-01 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0009_trip_budget_estimate_non_negative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency_code', models.CharField(max_length=3)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collected_expenses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='expenses.expense')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('EXPENSE_CREATED', 'Expense created'), ('EXPENSE_UPDATED', 'Expense updated'), ('CONTRIBUTION_SET', 'Contribution set'), ('CONTRIBUTION_REMOVED', 'Contribution removed'), ('SETTLEMENT_FINALIZED', 'Settlement finalized'), ('SETTLEMENT_REOPENED', 'Settlement reopened'), ('TRANSFER_MARKED_SENT', 'Transfer marked sent'), ('TRANSFER_CONFIRMED_RECEIVED', 'Transfer confirmed received')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='expenses.expense')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_ledger_entries', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name_snapshot', models.CharField(max_length=161)),
                ('identify_tag_snapshot', models.CharField(blank=True, max_length=32, null=True)),
                ('share_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='expenses.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('FINALIZED', 'Finalized'), ('REOPENED', 'Reopened')], max_length=12)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payer_marked_sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_payments', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_receipts', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='expenses.tripsettlement')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['trip', 'created_at'], name='expenses_ex_trip_id_c1aaa0_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='expense_total_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expensecontribution',
            constraint=models.UniqueConstraint(fields=('expense', 'user'), name='expensecontribution_unique_expense_user'),
        ),
        migrations.AddConstraint(
            model_name='expensecontribution',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='expensecontribution_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='expenseledgerentry',
            index=models.Index(fields=['trip', 'created_at'], name='expenses_ex_trip_id_d2afe2_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseledgerentry',
            index=models.Index(fields=['expense', 'created_at'], name='expenses_ex_expense_e0e1ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='expenseparticipant',
            constraint=models.UniqueConstraint(fields=('expense', 'user'), name='expenseparticipant_unique_expense_user'),
        ),
        migrations.AddConstraint(
            model_name='expenseparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('share_amount__gte', 0)), name='expenseparticipant_share_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='tripsettlement',
            index=models.Index(fields=['trip', 'status', 'created_at'], name='expenses_tr_trip_id_f7a8ed_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripsettlement',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'FINALIZED')), fields=('trip',), name='tripsettlement_unique_finalized_per_trip'),
        ),
        migrations.AddConstraint(
            model_name='settlementtransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='settlementtransfer_amount_positive'),
        ),
    ]
