# Generated by Django 5.2.13 on 2026-05-12 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0006_chatmessage_ai_status_chatmessage_sender_kind'),
        ('trips', '0009_trip_budget_estimate_non_negative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('provider', models.CharField(default='deepseek', max_length=32)),
                ('model', models.CharField(default='deepseek-v4-flash', max_length=64)),
                ('prompt', models.TextField()),
                ('error_code', models.CharField(blank=True, choices=[('TIMEOUT', 'Timeout'), ('RATE_LIMIT', 'Rate limit'), ('INSUFFICIENT_BALANCE', 'Insufficient balance'), ('PROVIDER_UNAVAILABLE', 'Provider unavailable'), ('PROVIDER_BAD_RESPONSE', 'Provider bad response'), ('CONFIG_MISSING', 'Config missing'), ('TASK_ERROR', 'Task error')], max_length=32, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('total_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('lock_expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_prompt_interaction', to='chat.chatmessage')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_ai_interactions', to=settings.AUTH_USER_MODEL)),
                ('response_message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_response_interaction', to='chat.chatmessage')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_interactions', to='trips.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['trip', 'status', 'lock_expires_at'], name='ai_interac_trip_st_lock_idx')],
            },
        ),
    ]
