# Generated by Django 5.2.13 on 2026-05-13 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('chat', '0006_chatmessage_ai_status_chatmessage_sender_kind'),
        ('trips', '0009_trip_budget_estimate_non_negative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIActionDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('NEEDS_INFO', 'Needs info'), ('READY', 'Ready'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('FAILED', 'Failed')], default='NEEDS_INFO', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('preview', models.JSONField(default=dict)),
                ('missing_fields', models.JSONField(default=list)),
                ('preconditions', models.JSONField(default=dict)),
                ('required_confirmation', models.CharField(max_length=32)),
                ('result', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_detail', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_drafts', to='ai.aiinteraction')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('response_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_action_drafts', to='chat.chatmessage')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_action_drafts', to='trips.trip')),
            ],
            options={
                'indexes': [models.Index(fields=['trip', 'status', 'expires_at'], name='ai_draft_trip_status_exp_idx'), models.Index(fields=['response_message', 'created_at'], name='ai_draft_response_idx')],
            },
        ),
    ]
