# Generated by Django 5.2.13 on 2026-05-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiactiondraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiactiondraft',
            name='display',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiactiondraft',
            name='summary',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='tool_calls_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
