# Generated by Django 5.2.13 on 2026-05-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_ai_overhaul_phase1'),
        ('chat', '0006_chatmessage_ai_status_chatmessage_sender_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiactiondraft',
            name='response_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_action_drafts', to='chat.chatmessage'),
        ),
    ]
