# Generated by Django 5.2.13 on 2026-05-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_aiactiondraft_response_message_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinteraction',
            name='error_code',
            field=models.CharField(blank=True, choices=[('TIMEOUT', 'Timeout'), ('RATE_LIMIT', 'Rate limit'), ('INSUFFICIENT_BALANCE', 'Insufficient balance'), ('PROVIDER_UNAVAILABLE', 'Provider unavailable'), ('PROVIDER_BAD_RESPONSE', 'Provider bad response'), ('CONFIG_MISSING', 'Config missing'), ('TASK_ERROR', 'Task error'), ('INTERNAL_ERROR', 'Internal error'), ('TOOL_UNKNOWN', 'Tool unknown'), ('TOOL_VALIDATION_FAILED', 'Tool validation failed')], max_length=32, null=True),
        ),
    ]
