# Generated by Django 5.2.6 on 2026-03-14 12:05

import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def resolve_bilateral_pending_duplicates(apps, schema_editor):
    """Cancel duplicate bilateral PENDING requests before adding the constraint.

    When A→B and B→A are both PENDING, keep the older one and cancel the newer.
    """
    FriendRequest = apps.get_model("friends", "FriendRequest")
    pending = list(
        FriendRequest.objects.filter(status="PENDING").order_by("created_at")
    )

    seen = set()
    for fr in pending:
        pair = (min(fr.sender_id, fr.receiver_id), max(fr.sender_id, fr.receiver_id))
        if pair in seen:
            fr.status = "CANCELLED"
            fr.resolved_at = timezone.now()
            fr.save(update_fields=["status", "resolved_at", "updated_at"])
        else:
            seen.add(pair)


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='fr_unique_pending_per_direction',
        ),
        migrations.RunPython(
            resolve_bilateral_pending_duplicates,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Least('sender', 'receiver'), django.db.models.functions.comparison.Greatest('sender', 'receiver'), condition=models.Q(('status', 'PENDING')), name='fr_unique_pending_bilateral'),
        ),
    ]
